version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: backend-db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_LOCAL}
      - POSTGRES_USER=${POSTGRES_USER_LOCAL}
      - POSTGRES_DB=${POSTGRES_DB_LOCAL}

volumes:
  postgres:
    name: backend